### ISSUE TITLE
Turning plans into action

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#16]
My tentative goal is to take the following items to social entrepreneurs late this week or early next week:

- [Our pitch](https://github.com/nedtwigg/mytake/wiki/Pitch)
- [Our design](https://github.com/nedtwigg/mytake/wiki/Design)
- A preliminary budget, including money, time, server resources, and legal resources that we will need to actually launch this thing ([issues with implementation label](https://github.com/nedtwigg/mytake/issues?q=is%3Aissue+is%3Aopen+label%3Aimplementation)).

Should he choose to accept, I think @WebsByTodd is going to bear the brunt of this project, at least at the beginning.  It's very frontend focused, and he's our frontend guy.  Even if we aren't able to get the resources needed to launch the entire project, I'd like to at least get the resources needed for Todd to work on this fulltime ASAP, especially the Editor MVP #10.

It's not my intention at all to stop the discussions we are having on our open strategy issues.  We can still change our whole plan if we want.  But for all the possibilities we are currently considering, I think whether we can make #10 work turns out to be the cornerstone.

Too fast?  Am I obsessing too much over #10, when the real issue is somewhere else?

**Comment by hattersv** [comment]
Hey guys, how are you?  My crazy travel and visiting guests schedule should end soon and I'll start on those documents.  Let me know when you need us to send us the donation we promised.  I think that Ned is getting married and is in Spain around this time?  Looking forward to engaging.  My actual job actually ends on July 14th!   Hope that you are enjoying the beginning of summer!

**Comment by nedtwigg** [comment]
Yup, I got married Saturday!  Leaving for honeymoon tomorrow, I'll be back Sunday July 2nd.  We don't need a donation until we have a 501(c) setup so that it can have a bank account.

**Comment by hattersv** [comment]
Now that Ned is back we should have a call to discuss setting up the documents because there are some decisions that need to be made in order to move forward. The first one is in which state we are incorporating.  We also need to determine in which states we are fundraising because most states have their own regulations and filing procedures.  There is a company called Harbor Compliance that can help us for a price-around $1500.   I did talk to them initially and they did say we don't have to do all this in order to raise funds right now, indicating that people can still get the text adduction once the 501 C-3 is formed, but I'd like to get more clarity on that. We also need to talk about a Board of Directors. But timelines in the next couple of weeks work for you guys?

**Comment by WebsByTodd** [comment]
I'm available the evening of the 12th at the soonest. Any day after that will work for me also.

**Comment by nedtwigg** [comment]
Same as Todd.

**Comment by hattersv** [comment]
Ok, how about the 17th?  That is my first day of no longer working for PAREXEL, my old life.  This would be a great way to kick-off my new life.  Evenings only?  If so, suggest a time please.  Earlier is better, if possible.
