### ISSUE TITLE
Webpack and build

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#17]
While we're iterating on the editor MVP, we want the simplest possible deployment model.  For now, that means that everything in the `docs` folder of the `master` branch ends up getting served at https://nedtwigg.github.io/mytake/

We are building a fairly complex webapp, so we'll need to get a build/minify/asset bundler setup from the get-go.

I put in a vote for TypeScript and Webpack.  Todd might vote for react, but he's not sure.  FWIW, here's a quick React/Typescript/Webpack starter:

https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

**Comment by nedtwigg** [comment]
Todd, note that the proposal above is even simpler than what we talked about on the phone - there's no need to setup Travis to trigger a push to a special branch.  We *do* need to remember to run webpack before we commit, but that's fine.  Just need something quick and dirty to get started with.  Once we've got some tests, we can setup Travis to run CI, and eventually have it trigger a more robust deployment model when we outgrow this one.

**Comment by WebsByTodd** [comment]
Question: To bundle react and react-dom libraries with our code, or to include them externally? Either approach is possible by changing a small piece of the Webpack configuration file.

If we bundle react and react-dom with our code, we don't need an internet connection to code and test. How important is that to you Ned? Are there other benefits to this approach?

If we include them externally:
- The browser will cache the libraries between builds.
- Our builds will be smaller and faster. 
- If we need to use something that can't be bundled with Webpack and requires React, we will need to use this approach so that React isn't imported more than once.
- If our project becomes something modular that other people import and include in their own projects, we will need to use this approach.
- The React version is specified in the URL we use to access it, so we won't have to worry about updates to React impacting our build.

The external approach seems to be standard. See:
https://www.typescriptlang.org/docs/handbook/react-&-webpack.html#create-a-webpack-configuration-file

**Comment by nedtwigg** [comment]
For now, lets optimize for fast development => small fast builds => external.

Once we have a full application, we can do testing to see if we can help initial load performance via bundling.

**Comment by hattersv** [comment]
Hi there-just wanted you to know that I think my work situation will look better in mid June and I'll start working on those documents. I'm not sure how to address the issue of the donation for the prototype. Have you set up an account and are you ready for the money?

**Comment by WebsByTodd** [comment]
https://github.com/nedtwigg/mytake/commit/242a2775d92333af52068e91928fa628a12ba019

**Comment by hattersv** [comment]
Hi Ned and Todd - we are catching up on everything having returned from our
journies and wanted to check in on the filing etc.  I know I was last
minute on some information, so wanted to check on that.

For some reason I can't find the area with this info in GitHub - I know
that you added it there, right?  I did check the wiki, and the 501 c3 issue.

Just want to help with the timeline if necessary.

Thanks for letting us know!

**Comment by nedtwigg** [comment]
Hope you had fun!  You weren't last minute - I had already submitted the first form a few weeks ago (PB-501(c)(3) that makes us a CA corp), and the info I was asking for is for the next form that I can't file until we get that back from CA.  And, coincidentally, the certified copy arrived in my mailbox today!  [Here we are in the CA database!](https://businesssearch.sos.ca.gov/CBS/SearchResults?SearchType=CORP&SearchCriteria=MyTake.org&SearchSubType=Keyword)

So now we're a CA corp, and tomorrow I'll be filing the next two forms (SI-100, which is what the questions to you were for, and the SS-4, which gives us a federal EIN (SSN for corp).  Then we can open our bank account.

We're still on track with this schedule: https://docs.google.com/spreadsheets/d/16utzGc4Dr5EWEolFOOnnM8hbviPueydDTow7KLzNlAI/edit#gid=0

The issue you're looking for is #13, you can find it using the search at the top of the issues page.

**Comment by hattersv** [comment]
Awesome, thanks!!
