### ISSUE TITLE
Investigate Brigade

### ISSUE THREAD

**Issue by nedtwigg** [nedtwigg/mytake#6]
[Brigade](https://www.brigade.com/) is a social network for voters.  They raised [$9.5mm](https://angel.co/brigade) in April 2014 and have Ron Conway and Sean Parker as backers (big time fancypants).  We should see if we can learn anything from them.

**Comment by WebsByTodd** [comment]
I signed up today. Very cool. It encourages each user to engage, rather than to read. Agree or disagree on an issue and leave your comments. The most up-voted comment is called the "leading reason". Also has a really cool "take 5 positions" feature on a current issue to get you started on engagement.
